apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
  labels:
    app: keycloak
  namespace: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  labels:
    app: keycloak
  namespace: keycloak
spec:
  clusterIP: None
  selector:
    app: keycloak
  ports:
    - name: jgroups
      port: 7800
      targetPort: 7800

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:21.0.2
        args: ["start"]
        env:
        - name: KEYCLOAK_ADMIN
          value: 'admin'
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: 'admin'
        - name: KC_PROXY
          value: "edge"
        - name: KC_HOSTNAME
          value: keycloak.192.168.56.6.nip.io  
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: 'false'
        - name: KC_DB
          value: 'postgres'
        - name: KC_DB_URL
          value: 'jdbc:postgresql://postgres/keycloak'
        - name: KC_DB_USERNAME
          value: keycloak
        - name: KC_DB_PASSWORD
          value: keycloak
        - name: KC_DB_SCHEMA
          value: public
        # - name: KC_TRANSACTION_XA_ENABLED
        #   value: 'true'
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_LOG_LEVEL
          value: 'INFO'
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: keycloak
        ports:
          - name: http
            containerPort: 8080
          - name: jgroups
            containerPort: 7800       
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /realms/master
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 1
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
          requests:
            memory: "256Mi"
            cpu: "0.2"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
spec:
  tls:
    - hosts:
        - keycloak.192.168.56.6.nip.io
  rules:
    - host: keycloak.192.168.56.6.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-svc
                port:
                  name: http
                  